In [46]:
# load CVDRisk_estimator_BP.pkl from output folder
import pickle

with open('CVDRisk_estimator_BP.pkl', 'rb') as f:
    model = pickle.load(f)
    f.close()

print(model.coef_)
print(model.intercept_)

[ 0.08647672 -0.71599168 -0.33732405  0.02057186  0.03697464  0.0296318
  0.05699702  0.00443684  0.71938144  0.29171093 -0.01786874 -0.02156886
  0.02849388 -0.01090756]
-6.768294370801318


In [8]:
x = [62.3, 1.,         1.,         0.,         0.,         1.,
  0.,        28.5119667,  0.,         0.,         0.,         0.,
  0.,         0.,       ]

import numpy as np
X = np.array(x).reshape(1, -1)
print(X)
print(X.shape)
print('model.predict(X)', model.predict(X))

print('manual calculation:')

coeef = list(model.coef_)
intercep = [model.intercept_]
print(coeef)
print(intercep)

[[62.3        1.         1.         0.         0.         1.
   0.        28.5119667  0.         0.         0.         0.
   0.         0.       ]]
(1, 14)
model.predict(X) [-2.27797532]
manual calculation:
[0.08647672345597548, -0.7159916795088349, -0.3373240485386988, 0.020571862587462745, 0.03697463763512505, 0.029631800185378327, 0.05699701653020533, 0.004436842599651939, 0.7193814446747889, 0.291710927154881, -0.017868742059401813, -0.021568858038188452, 0.02849387935159807, -0.010907556840188879]
[-6.768294370801318]


In [11]:
wt_vec = np.array(coeef)
print(wt_vec)

[ 0.08647672 -0.71599168 -0.33732405  0.02057186  0.03697464  0.0296318
  0.05699702  0.00443684  0.71938144  0.29171093 -0.01786874 -0.02156886
  0.02849388 -0.01090756]


In [12]:
res = np.dot(wt_vec, X.T) + intercep
print(res)

[-2.27797532]


In [47]:
# load the x_train.pkl from output folder
with open('x_train.pkl', 'rb') as f:
    x_train = pickle.load(f)

print(x_train.shape)
# print('x_train: \n', x_train)

# load the cvdrisk.pkl from output folder
with open('cvdrisk.pkl', 'rb') as f:
    cvdrisk = pickle.load(f)

print(cvdrisk.shape)
print('cvdrisk: \n', cvdrisk)

y_true_model_pred = model.predict(x_train)
y_true = 1.0/(1.0+np.exp(-y_true_model_pred))

# convert y_true's second dimension to 1
y_true = y_true.reshape(-1, 1)

print('y_true: \n', y_true)
print('y_true.shape: \n', y_true.shape)

# calculate cvdrisk - y_true
diff = cvdrisk - y_true
print('diff: \n', diff)
print('max diff: \n', np.max(diff))


(20, 14)
(20, 1)
cvdrisk: 
 [[0.15007779]
 [0.11541242]
 [0.11541242]
 [0.11541242]
 [0.11541242]
 [0.09296354]
 [0.09296354]
 [0.09296354]
 [0.09296354]
 [0.09296354]
 [0.09296354]
 [0.09296354]
 [0.09296354]
 [0.11541242]
 [0.11541242]
 [0.11541242]
 [0.11541242]
 [0.09296354]
 [0.09296354]
 [0.08880447]]
y_true: 
 [[0.15007779]
 [0.11541242]
 [0.11541242]
 [0.11541242]
 [0.11541242]
 [0.09296354]
 [0.09296354]
 [0.09296354]
 [0.09296354]
 [0.09296354]
 [0.09296354]
 [0.09296354]
 [0.09296354]
 [0.11541242]
 [0.11541242]
 [0.11541242]
 [0.11541242]
 [0.09296354]
 [0.09296354]
 [0.08880447]]
y_true.shape: 
 (20, 1)
diff: 
 [[0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]]
max diff: 
 0.0


In [44]:
# use a linear regression model to fit x_train and cvdrisk
from sklearn.linear_model import LinearRegression
y = cvdrisk
y_train = -np.log((1.0-y)/y) 
y_train = y_train[:,0]
print('y_train.shape: \n', y_train.shape)

reg = LinearRegression().fit(x_train, y_train)
print('reg.coef_: \n', reg.coef_)
print('reg.intercept_: \n', reg.intercept_)
print('reg.score(x_train, cvdrisk): \n', reg.score(x_train, y_train))

# print the coefficients of model
print('model.coef_: \n', model.coef_)
print('model.intercept_: \n', model.intercept_)


y_train.shape: 
 (20,)
reg.coef_: 
 [ 3.74390086e-04  1.70286528e-13  5.27144994e-12  2.61818345e-13
  0.00000000e+00  0.00000000e+00  0.00000000e+00 -1.24796696e-04
  0.00000000e+00  2.91710927e-01 -1.97188000e-02 -1.97188000e-02
  0.00000000e+00 -1.09075568e-02]
reg.intercept_: 
 -2.2977416220296676
reg.score(x_train, cvdrisk): 
 1.0
model.coef_: 
 [ 0.08647672 -0.71599168 -0.33732405  0.02057186  0.03697464  0.0296318
  0.05699702  0.00443684  0.71938144  0.29171093 -0.01786874 -0.02156886
  0.02849388 -0.01090756]
model.intercept_: 
 -6.768294370801318


In [48]:
x_train = np.load('X.npy')
print('x_train.shape:', x_train.shape)
y_train = np.load('y.npy')
print('y_train.shape:', y_train.shape)


reg = LinearRegression().fit(x_train, y_train)
print('reg.coef_: \n', reg.coef_)
print('reg.intercept_: \n', reg.intercept_)
print('reg.score(x_train, cvdrisk): \n', reg.score(x_train, y_train))

x_train.shape: (176880, 14)
y_train.shape: (176880,)
reg.coef_: 
 [ 0.08647672 -0.71599168 -0.33732405  0.02057186  0.03697464  0.0296318
  0.05699702  0.00443684  0.71938144  0.29171093 -0.01786874 -0.02156886
  0.02849388 -0.01090756]
reg.intercept_: 
 -6.768294370801318
reg.score(x_train, cvdrisk): 
 0.7918751124374861
